name: Mike Arvela
markdown: kramdown
highlighter: rouge
timezone: Europe/Helsinki
encoding: UTF-8
permalink: /:title
safe: true
lsi: false
include: [".well-known"]
sass:
  sass_dir: _sass
plugins:
  - jekyll-redirect-from
  - jekyll-last-modified-at

site_name: Mike
site_title: Mike Arvela
site_description: Hi! I'm Mike, a web developer from Tampere, Finland.
