name: Mike Arvela
markdown: redcarpet
highlighter: pygments
timezone: Europe/Helsinki
encoding: UTF-8
permalink: /:title
safe: true
lsi: false
include: [".well-known"]
sass:
    sass_dir: _sass
gems:
  - jekyll-redirect-from
